import Service from '@ember/service';
export default class RoleTypeService extends Service {
  PARTY_ROLE_PERSON = "PARTY_ROLE_PERSON";
  PARTY_ROLE_ORGANIZATION = "PARTY_ROLE_ORGANIZATION";

  USER_ROLE_ADMIN = "USER_ROLE_ADMIN";
  USER_ROLE_SUPER_USER = "USER_ROLE_SUPER_USER";
  USER_ROLE_OPERATOR = "USER_ROLE_OPERATOR";
  USER_ROLE_CUSTOMER = "USER_ROLE_CUSTOMER";

  PERSON_ROLE_EMPLOYEE = "PERSON_ROLE_EMPLOYEE";
  PERSON_ROLE_CLIENT = "PERSON_ROLE_CLIENT";
  PERSON_ROLE_ORGANIZATION_ACCESS = "PERSON_ROLE_ORGANIZATION_ACCESS";
  PERSON_ROLE_FACILITY_ACCESS = "PERSON_ROLE_FACILITY_ACCESS";
  PERSON_ROLE_READ_ONLY_ORGANIZATION_ACCESS = 'PERSON_ROLE_READ_ONLY_ORGANIZATION_ACCESS';

  ORG_ROLE_ORGANIZATION = "ORG_ROLE_ORGANIZATION";
  ORG_ROLE_SUB_ORGANIZATION = "ORG_ROLE_SUB_ORGANIZATION";

  FACILITY_PARTY_ROLE_OWNER = "FACILITY_PARTY_ROLE_OWNER";
  FACILITY_PARTY_ROLE_RESTRICTED = "FACILITY_PARTY_ROLE_RESTRICTED";
  FACILITY_PARTY_ROLE_USER_ASSOC = "FACILITY_PARTY_ROLE_USER_ASSOC";


  USER_ROLE_ADMIN_ID = 1;
  USER_ROLE_SUPER_USER_ID = 2;
  USER_ROLE_OPERATOR_ID = 3;
  USER_ROLE_CUSTOMER_ID = 4;

  PARTY_ROLE_PERSON_ID = 5;
  PARTY_ROLE_ORGANIZATION_ID = 6;

  PERSON_ROLE_EMPLOYEE_ID = 7;
  PERSON_ROLE_CLIENT_ID = 8;
  PERSON_ROLE_ORGANIZATION_ACCESS_ID = 19;
  PERSON_ROLE_FACILITY_ACCESS_ID = 20;
  PERSON_ROLE_READ_ONLY_ORGANIZATION_ACCESS_ID = 21;

  ORG_ROLE_ORGANIZATION_ID = 9;
  ORG_ROLE_SUB_ORGANIZATION_ID = 10;

  FACILITY_PARTY_ROLE_OWNER_ID = 16;
  FACILITY_PARTY_ROLE_RESTRICTED_ID = 17;
  FACILITY_PARTY_ROLE_USER_ASSOC_ID = 18;
}
